<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiClientes.DTOs\ApiClientes.DTOs.csproj" />
    <ProjectReference Include="..\ApiClientes.Models\ApiClientes.Models.csproj" />
    <ProjectReference Include="..\ApiClientes.Repositories\ApiClientes.Repositories.csproj" />
  </ItemGroup>

</Project>
